// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
    public static final int defaultTimeout = 30; //milliseconds

    public static final class DriveConstants {
        public static final double joystickYPower = 1.3;
        public static final double joystickXPower = 1.8;
        public static final double joystickYScale = 0.8;
    }

    public static final class AutoConstants {
        public static final double autoTime = 5;
        public static final double autoSpeed = .8;
    }

    public static final class ExtenderConstants {
        public static final double positionTolerance = 0.5;

        public static final double extendPosition = 10;
        public static final double retractPosition = 3;
        public static final double extenderPower = 0.2;
    }

    public static final class GripperConstants {
        public static final double forwardSoftLimit = 100;
        public static final double backwardSoftLimit = -100;

        public static final double openPosition = 1;
        public static final double closePosition = 2;
    }

    public static final class ArmConstants {
        public static final double armPower = 0.5;
        public static final double positionTolerance = 0.05;

        public static final double forwardPosition = 0;
        public static final double backwardPosition = 0;

        // these are all on the front of the robot, for now
        public static final double intakePosition = 0;
        public static final double lowPlacePosition = 0;
        public static final double midPlacePosition = 0;
        public static final double highPlacePositon = 0;
        public static final double stowPosition = 0;
    }



   /**
    * public static final class DriveConstants {
    *   public static final int kLeftMotor1Port = 0;
    *   public static final int kLeftMotor2Port = 1;
    *   public static final int kRightMotor1Port = 2;
    *   public static final int kRightMotor2Port = 3; 
    * }
    */ 
}

